const keyMirror = require('keymirror');

module.exports = keyMirror({
  CLIENT_UID: null,
  UID_CLIENT: null,
  CLIENT_ID_COUNTER: null,
  TOOLS_ORDER: null,
  UID: null,
  OPERATIONS_LIST: null,
  PROJECT_OPERATIONS: null,
  PROJECT_DATA: null,
  USER_OPERATIONS: null,
  CLIENT_OPERATIONS: null,
  PROJECT_CLIENTS: null,
  USER_CLIENTS: null,
  FILLABLE_VERSION: null,
  EDITOR_DATA: null,
  LOCAL_ID: null,
  CONFIG_XML: null,
  DATA_DELIVERY: null,
  QUEUE_REMOVE: null,
  ACCESS: null,
  CROSS_EDITOR: null,
  EDITOR_MODE: null,
  VERSIONS_OPERATIONS: null,
  AUTH_CACHE: null,
});
