const DOCUMENT_CONTENT_STATUS = {
  PENDING: 'PENDING',
  FINISHED: 'FINISHED',
  ERROR: 'ERROR',
};

const DOCUMENT_CONTENT_STATUS_CODE = {
  PENDING: 202,
  FINISHED: 200,
  ERROR: 424,
};

module.exports = () => ({
  DOCUMENT_CONTENT_STATUS,
  DOCUMENT_CONTENT_STATUS_CODE,
});
